# Data processing of Business Funding Data in Nigeria

## Objective: You are tasked with analyzing and pre-processing a dataset (Business Funding Data.csv) containing business funding information in Nigeria. Your goal is to prepare the data for further analysis by applying various preprocessing techniques.

In [2]:
# Installation
!pip install pandas
!pip install numpy
!pip install scikit-learn

Requirement already satisfied: pandas in c:\users\dell\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in c:\users\dell\anaconda3\lib\site-packages (2.1.3)
Requirement already satisfied: scikit-learn in c:\users\dell\anaconda3\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

In [3]:
# import libraries
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel(r"C:\Users\DELL\OneDrive\Documents\DA\01-Raw-Datasets\Business Funding Data Excel.xlsx")
df.head()

,Website Domain,Effective date,Found At,Financing Type,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,NaN,2024-03-14T01:00:00+01:00,NaN,NaN,[],NaN,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,NaN,2024-05-31T02:00:00+02:00,NaN,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,NaN,2024-07-24T02:00:00+02:00,NaN,NaN,"[""private_equity""]",NaN,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,NaN,2024-05-01T02:00:00+02:00,NaN,NaN,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,NaN,2024-04-11T02:00:00+02:00,NaN,NaN,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Website Domain             26 non-null     object
 1   Effective date             6 non-null      object
 2   Found At                   26 non-null     object
 3   Financing Type             8 non-null      object
 4   Financing Type Normalized  8 non-null      object
 5   Categories                 26 non-null     object
 6   Investors                  13 non-null     object
 7   Investors Count            13 non-null     float64
 8   Amount                     26 non-null     object
 9   Amount Normalized          26 non-null     int64
 10  Source Urls                26 non-null     object
dtypes: float64(1), int64(1), object(9)
memory usage: 2.4+ KB

## Missing Value

In [19]:
len(df)

26

In [20]:
# Checking for the percentage of missing/null valus
missing_percentage=df.isnull().sum()/len(df) * 100
missing_percentage

Website Domain                0.000000
Effective date               76.923077
Found At                      0.000000
Financing Type               69.230769
Financing Type Normalized    69.230769
Categories                    0.000000
Investors                    50.000000
Investors Count              50.000000
Amount                        0.000000
Amount Normalized             0.000000
Source Urls                   0.000000
dtype: float64

In [21]:
#Checking for missing/null values
df.isnull().sum()

Website Domain                0
Effective date               20
Found At                      0
Financing Type               18
Financing Type Normalized    18
Categories                    0
Investors                    13
Investors Count              13
Amount                        0
Amount Normalized             0
Source Urls                   0
dtype: int64

In [22]:
# Checking for unique values in Effective date column 
df['Effective date'].unique()

array([nan, '2024-04-18T02:00:00+02:00', '2024-04-16T02:00:00+02:00',
       '2024-06-20T02:00:00+02:00', '2024-04-24T02:00:00+02:00',
       '2024-06-26T02:00:00+02:00', '2024-06-27T02:00:00+02:00'],
      dtype=object)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Website Domain             26 non-null     object
 1   Effective date             6 non-null      object
 2   Found At                   26 non-null     object
 3   Financing Type             8 non-null      object
 4   Financing Type Normalized  8 non-null      object
 5   Categories                 26 non-null     object
 6   Investors                  13 non-null     object
 7   Investors Count            13 non-null     float64
 8   Amount                     26 non-null     object
 9   Amount Normalized          26 non-null     int64
 10  Source Urls                26 non-null     object
dtypes: float64(1), int64(1), object(9)
memory usage: 2.4+ KB

In [190]:
df['Effective date'].mode()[0]

'2024-04-16T02:00:00+02:00'

In [24]:
df['Effective date'].fillna(df['Effective date'].mode()[0], inplace=True)
df

C:\Users\DELL\AppData\Local\Temp\ipykernel_16328\2248497416.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Effective date'].fillna(df['Effective date'].mode()[0], inplace=True)

,Website Domain,Effective date,Found At,Financing Type,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-04-16T02:00:00+02:00,2024-03-14T01:00:00+01:00,NaN,NaN,[],NaN,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-04-16T02:00:00+02:00,2024-05-31T02:00:00+02:00,NaN,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,2024-04-16T02:00:00+02:00,2024-07-24T02:00:00+02:00,NaN,NaN,"[""private_equity""]",NaN,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,2024-04-16T02:00:00+02:00,2024-05-01T02:00:00+02:00,NaN,NaN,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-16T02:00:00+02:00,2024-04-11T02:00:00+02:00,NaN,NaN,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-18T02:00:00+02:00,2024-04-24T02:00:00+02:00,Series B,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16T02:00:00+02:00,2024-04-16T02:00:00+02:00,NaN,NaN,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,2024-04-16T02:00:00+02:00,2024-08-07T02:00:00+02:00,Series I,series_i,"[""series_i"", ""venture""]",NaN,NaN,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,2024-04-16T02:00:00+02:00,2024-07-08T02:00:00+02:00,NaN,NaN,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,2024-04-16T02:00:00+02:00,2024-04-18T02:00:00+02:00,NaN,NaN,[],NaN,NaN,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,2024-04-16T02:00:00+02:00,2024-03-26T01:00:00+01:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,2024-04-16T02:00:00+02:00,2024-05-09T02:00:00+02:00,NaN,NaN,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,2024-04-16T02:00:00+02:00,2024-07-16T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,2024-04-16T02:00:00+02:00,2024-07-15T02:00:00+02:00,NaN,NaN,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,2024-04-16T02:00:00+02:00,2024-06-05T02:00:00+02:00,NaN,NaN,[],NaN,NaN,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,2024-04-16T02:00:00+02:00,2024-06-27T02:00:00+02:00,Series A2,series_a2,"[""series_a2"", ""venture""]",NaN,NaN,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-25T02:00:00+02:00,NaN,NaN,[],NaN,NaN,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,2024-04-16T02:00:00+02:00,2024-04-10T02:00:00+02:00,NaN,NaN,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-20T02:00:00+02:00,2024-06-18T02:00:00+02:00,NaN,NaN,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24T02:00:00+02:00,2024-04-24T02:00:00+02:00,NaN,NaN,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26T02:00:00+02:00,2024-06-26T02:00:00+02:00,NaN,NaN,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-30T02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27T02:00:00+02:00,2024-06-27T02:00:00+02:00,Series A,series_a,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,2024-04-16T02:00:00+02:00,2024-05-22T02:00:00+02:00,NaN,NaN,"[""private_equity"", ""venture""]",NaN,NaN,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,NaN,NaN,[],NaN,NaN,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [194]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Website Domain             26 non-null     object
 1   Effective date             26 non-null     object
 2   Found At                   26 non-null     object
 3   Financing Type             8 non-null      object
 4   Financing Type Normalized  8 non-null      object
 5   Categories                 26 non-null     object
 6   Investors                  13 non-null     object
 7   Investors Count            13 non-null     float64
 8   Amount                     26 non-null     object
 9   Amount Normalized          26 non-null     int64
 10  Source Urls                26 non-null     object
dtypes: float64(1), int64(1), object(9)
memory usage: 2.4+ KB

In [25]:
df.drop(columns=['Financing Type'], inplace=True)
df

,Website Domain,Effective date,Found At,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-04-16T02:00:00+02:00,2024-03-14T01:00:00+01:00,NaN,[],NaN,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-04-16T02:00:00+02:00,2024-05-31T02:00:00+02:00,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,2024-04-16T02:00:00+02:00,2024-07-24T02:00:00+02:00,NaN,"[""private_equity""]",NaN,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,2024-04-16T02:00:00+02:00,2024-05-01T02:00:00+02:00,NaN,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-16T02:00:00+02:00,2024-04-11T02:00:00+02:00,NaN,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-18T02:00:00+02:00,2024-04-24T02:00:00+02:00,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16T02:00:00+02:00,2024-04-16T02:00:00+02:00,NaN,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,2024-04-16T02:00:00+02:00,2024-08-07T02:00:00+02:00,series_i,"[""series_i"", ""venture""]",NaN,NaN,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,2024-04-16T02:00:00+02:00,2024-07-08T02:00:00+02:00,NaN,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,2024-04-16T02:00:00+02:00,2024-04-18T02:00:00+02:00,NaN,[],NaN,NaN,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,2024-04-16T02:00:00+02:00,2024-03-26T01:00:00+01:00,seed,"[""seed"", ""venture""]",NaN,NaN,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,2024-04-16T02:00:00+02:00,2024-05-09T02:00:00+02:00,NaN,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,2024-04-16T02:00:00+02:00,2024-07-16T02:00:00+02:00,seed,"[""seed"", ""venture""]",NaN,NaN,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,2024-04-16T02:00:00+02:00,2024-07-15T02:00:00+02:00,NaN,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,2024-04-16T02:00:00+02:00,2024-06-05T02:00:00+02:00,NaN,[],NaN,NaN,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,2024-04-16T02:00:00+02:00,2024-06-27T02:00:00+02:00,series_a2,"[""series_a2"", ""venture""]",NaN,NaN,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-25T02:00:00+02:00,NaN,[],NaN,NaN,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,2024-04-16T02:00:00+02:00,2024-04-10T02:00:00+02:00,NaN,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-20T02:00:00+02:00,2024-06-18T02:00:00+02:00,NaN,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24T02:00:00+02:00,2024-04-24T02:00:00+02:00,NaN,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,seed,"[""seed"", ""venture""]",NaN,NaN,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26T02:00:00+02:00,2024-06-26T02:00:00+02:00,NaN,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-30T02:00:00+02:00,seed,"[""seed"", ""venture""]",NaN,NaN,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27T02:00:00+02:00,2024-06-27T02:00:00+02:00,series_a,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,2024-04-16T02:00:00+02:00,2024-05-22T02:00:00+02:00,NaN,"[""private_equity"", ""venture""]",NaN,NaN,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,NaN,[],NaN,NaN,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [199]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Website Domain             26 non-null     object
 1   Effective date             26 non-null     object
 2   Found At                   26 non-null     object
 3   Financing Type Normalized  8 non-null      object
 4   Categories                 26 non-null     object
 5   Investors                  13 non-null     object
 6   Investors Count            13 non-null     float64
 7   Amount                     26 non-null     object
 8   Amount Normalized          26 non-null     int64
 9   Source Urls                26 non-null     object
dtypes: float64(1), int64(1), object(8)
memory usage: 2.2+ KB

In [26]:
df.drop(columns=['Financing Type Normalized'], inplace=True)
df

,Website Domain,Effective date,Found At,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-04-16T02:00:00+02:00,2024-03-14T01:00:00+01:00,[],NaN,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-04-16T02:00:00+02:00,2024-05-31T02:00:00+02:00,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,2024-04-16T02:00:00+02:00,2024-07-24T02:00:00+02:00,"[""private_equity""]",NaN,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,2024-04-16T02:00:00+02:00,2024-05-01T02:00:00+02:00,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-16T02:00:00+02:00,2024-04-11T02:00:00+02:00,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-18T02:00:00+02:00,2024-04-24T02:00:00+02:00,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16T02:00:00+02:00,2024-04-16T02:00:00+02:00,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,2024-04-16T02:00:00+02:00,2024-08-07T02:00:00+02:00,"[""series_i"", ""venture""]",NaN,NaN,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,2024-04-16T02:00:00+02:00,2024-07-08T02:00:00+02:00,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,2024-04-16T02:00:00+02:00,2024-04-18T02:00:00+02:00,[],NaN,NaN,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,2024-04-16T02:00:00+02:00,2024-03-26T01:00:00+01:00,"[""seed"", ""venture""]",NaN,NaN,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,2024-04-16T02:00:00+02:00,2024-05-09T02:00:00+02:00,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,2024-04-16T02:00:00+02:00,2024-07-16T02:00:00+02:00,"[""seed"", ""venture""]",NaN,NaN,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,2024-04-16T02:00:00+02:00,2024-07-15T02:00:00+02:00,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,2024-04-16T02:00:00+02:00,2024-06-05T02:00:00+02:00,[],NaN,NaN,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,2024-04-16T02:00:00+02:00,2024-06-27T02:00:00+02:00,"[""series_a2"", ""venture""]",NaN,NaN,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-25T02:00:00+02:00,[],NaN,NaN,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,2024-04-16T02:00:00+02:00,2024-04-10T02:00:00+02:00,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-20T02:00:00+02:00,2024-06-18T02:00:00+02:00,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24T02:00:00+02:00,2024-04-24T02:00:00+02:00,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,"[""seed"", ""venture""]",NaN,NaN,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26T02:00:00+02:00,2024-06-26T02:00:00+02:00,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-30T02:00:00+02:00,"[""seed"", ""venture""]",NaN,NaN,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27T02:00:00+02:00,2024-06-27T02:00:00+02:00,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,2024-04-16T02:00:00+02:00,2024-05-22T02:00:00+02:00,"[""private_equity"", ""venture""]",NaN,NaN,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,[],NaN,NaN,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

df.info()

In [28]:
df['Investors Count'].mode()[0]

np.float64(1.0)

In [29]:
df['Investors Count'].fillna(df['Investors Count'].mode()[0], inplace=True)
df

C:\Users\DELL\AppData\Local\Temp\ipykernel_16328\3398068201.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Investors Count'].fillna(df['Investors Count'].mode()[0], inplace=True)

,Website Domain,Effective date,Found At,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-04-16T02:00:00+02:00,2024-03-14T01:00:00+01:00,[],NaN,1.0,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-04-16T02:00:00+02:00,2024-05-31T02:00:00+02:00,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,2024-04-16T02:00:00+02:00,2024-07-24T02:00:00+02:00,"[""private_equity""]",NaN,1.0,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,2024-04-16T02:00:00+02:00,2024-05-01T02:00:00+02:00,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-16T02:00:00+02:00,2024-04-11T02:00:00+02:00,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-18T02:00:00+02:00,2024-04-24T02:00:00+02:00,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16T02:00:00+02:00,2024-04-16T02:00:00+02:00,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,2024-04-16T02:00:00+02:00,2024-08-07T02:00:00+02:00,"[""series_i"", ""venture""]",NaN,1.0,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,2024-04-16T02:00:00+02:00,2024-07-08T02:00:00+02:00,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,2024-04-16T02:00:00+02:00,2024-04-18T02:00:00+02:00,[],NaN,1.0,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,2024-04-16T02:00:00+02:00,2024-03-26T01:00:00+01:00,"[""seed"", ""venture""]",NaN,1.0,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,2024-04-16T02:00:00+02:00,2024-05-09T02:00:00+02:00,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,2024-04-16T02:00:00+02:00,2024-07-16T02:00:00+02:00,"[""seed"", ""venture""]",NaN,1.0,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,2024-04-16T02:00:00+02:00,2024-07-15T02:00:00+02:00,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,2024-04-16T02:00:00+02:00,2024-06-05T02:00:00+02:00,[],NaN,1.0,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,2024-04-16T02:00:00+02:00,2024-06-27T02:00:00+02:00,"[""series_a2"", ""venture""]",NaN,1.0,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-25T02:00:00+02:00,[],NaN,1.0,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,2024-04-16T02:00:00+02:00,2024-04-10T02:00:00+02:00,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-20T02:00:00+02:00,2024-06-18T02:00:00+02:00,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24T02:00:00+02:00,2024-04-24T02:00:00+02:00,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,"[""seed"", ""venture""]",NaN,1.0,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26T02:00:00+02:00,2024-06-26T02:00:00+02:00,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,2024-04-16T02:00:00+02:00,2024-04-30T02:00:00+02:00,"[""seed"", ""venture""]",NaN,1.0,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27T02:00:00+02:00,2024-06-27T02:00:00+02:00,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,2024-04-16T02:00:00+02:00,2024-05-22T02:00:00+02:00,"[""private_equity"", ""venture""]",NaN,1.0,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,2024-04-16T02:00:00+02:00,2024-06-25T02:00:00+02:00,[],NaN,1.0,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Website Domain     26 non-null     object
 1   Effective date     26 non-null     object
 2   Found At           26 non-null     object
 3   Categories         26 non-null     object
 4   Investors          13 non-null     object
 5   Investors Count    26 non-null     float64
 6   Amount             26 non-null     object
 7   Amount Normalized  26 non-null     int64
 8   Source Urls        26 non-null     object
dtypes: float64(1), int64(1), object(7)
memory usage: 2.0+ KB

In [11]:
df['Investors'].fillna(df['Investors'].mode()[0], inplace=True)
df

C:\Users\DELL\AppData\Local\Temp\ipykernel_9932\2430120307.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Investors'].fillna(df['Investors'].mode()[0], inplace=True)

,Website Domain,Effective date,Found At,Financing Type,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,NaT,2024-03-14 01:00:00+01:00,NaN,NaN,[],accelia.vc,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,NaT,2024-05-31 02:00:00+02:00,NaN,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,NaT,2024-07-24 02:00:00+02:00,NaN,NaN,"[""private_equity""]",accelia.vc,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,NaT,2024-05-01 02:00:00+02:00,NaN,NaN,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,NaT,2024-04-11 02:00:00+02:00,NaN,NaN,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-18 02:00:00+02:00,2024-04-24 02:00:00+02:00,Series B,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16 02:00:00+02:00,2024-04-16 02:00:00+02:00,NaN,NaN,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,NaT,2024-08-07 02:00:00+02:00,Series I,series_i,"[""series_i"", ""venture""]",accelia.vc,NaN,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,NaT,2024-07-08 02:00:00+02:00,NaN,NaN,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,NaT,2024-04-18 02:00:00+02:00,NaN,NaN,[],accelia.vc,NaN,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,NaT,2024-03-26 01:00:00+01:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,NaN,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,NaT,2024-05-09 02:00:00+02:00,NaN,NaN,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,NaT,2024-07-16 02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,NaN,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,NaT,2024-07-15 02:00:00+02:00,NaN,NaN,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,NaT,2024-06-05 02:00:00+02:00,NaN,NaN,[],accelia.vc,NaN,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,NaT,2024-06-27 02:00:00+02:00,Series A2,series_a2,"[""series_a2"", ""venture""]",accelia.vc,NaN,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,NaT,2024-04-25 02:00:00+02:00,NaN,NaN,[],accelia.vc,NaN,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,NaT,2024-04-10 02:00:00+02:00,NaN,NaN,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-20 02:00:00+02:00,2024-06-18 02:00:00+02:00,NaN,NaN,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24 02:00:00+02:00,2024-04-24 02:00:00+02:00,NaN,NaN,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,NaT,2024-06-25 02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,NaN,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26 02:00:00+02:00,2024-06-26 02:00:00+02:00,NaN,NaN,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,NaT,2024-04-30 02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,NaN,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27 02:00:00+02:00,2024-06-27 02:00:00+02:00,Series A,series_a,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,NaT,2024-05-22 02:00:00+02:00,NaN,NaN,"[""private_equity"", ""venture""]",accelia.vc,NaN,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,NaT,2024-06-25 02:00:00+02:00,NaN,NaN,[],accelia.vc,NaN,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [27]:
df

,website_domain,effective_date,found_at,financing_type,financing_type_normalized,categories,investors,investors_count,amount,amount_normalized,source_urls
0,trafigura.com,NaT,2024-03-14 01:00:00+01:00,NaN,NaN,[],accelia.vc,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,NaT,2024-05-31 02:00:00+02:00,NaN,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,NaT,2024-07-24 02:00:00+02:00,NaN,NaN,"[""private_equity""]",accelia.vc,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,NaT,2024-05-01 02:00:00+02:00,NaN,NaN,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,NaT,2024-04-11 02:00:00+02:00,NaN,NaN,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-18 02:00:00+02:00,2024-04-24 02:00:00+02:00,Series B,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16 02:00:00+02:00,2024-04-16 02:00:00+02:00,NaN,NaN,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,NaT,2024-08-07 02:00:00+02:00,Series I,series_i,"[""series_i"", ""venture""]",accelia.vc,NaN,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,NaT,2024-07-08 02:00:00+02:00,NaN,NaN,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,NaT,2024-04-18 02:00:00+02:00,NaN,NaN,[],accelia.vc,NaN,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,NaT,2024-03-26 01:00:00+01:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,NaN,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,NaT,2024-05-09 02:00:00+02:00,NaN,NaN,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,NaT,2024-07-16 02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,NaN,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,NaT,2024-07-15 02:00:00+02:00,NaN,NaN,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,NaT,2024-06-05 02:00:00+02:00,NaN,NaN,[],accelia.vc,NaN,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,NaT,2024-06-27 02:00:00+02:00,Series A2,series_a2,"[""series_a2"", ""venture""]",accelia.vc,NaN,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,NaT,2024-04-25 02:00:00+02:00,NaN,NaN,[],accelia.vc,NaN,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,NaT,2024-04-10 02:00:00+02:00,NaN,NaN,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-20 02:00:00+02:00,2024-06-18 02:00:00+02:00,NaN,NaN,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24 02:00:00+02:00,2024-04-24 02:00:00+02:00,NaN,NaN,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,NaT,2024-06-25 02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,NaN,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26 02:00:00+02:00,2024-06-26 02:00:00+02:00,NaN,NaN,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,NaT,2024-04-30 02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,NaN,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27 02:00:00+02:00,2024-06-27 02:00:00+02:00,Series A,series_a,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,NaT,2024-05-22 02:00:00+02:00,NaN,NaN,"[""private_equity"", ""venture""]",accelia.vc,NaN,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,NaT,2024-06-25 02:00:00+02:00,NaN,NaN,[],accelia.vc,NaN,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [9]:
df

,Website Domain,Effective date,Found At,Financing Type,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,NaT,2024-03-14 01:00:00+01:00,NaN,NaN,[],NaN,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,NaT,2024-05-31 02:00:00+02:00,NaN,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,NaT,2024-07-24 02:00:00+02:00,NaN,NaN,"[""private_equity""]",NaN,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,NaT,2024-05-01 02:00:00+02:00,NaN,NaN,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,NaT,2024-04-11 02:00:00+02:00,NaN,NaN,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-18 02:00:00+02:00,2024-04-24 02:00:00+02:00,Series B,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16 02:00:00+02:00,2024-04-16 02:00:00+02:00,NaN,NaN,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,NaT,2024-08-07 02:00:00+02:00,Series I,series_i,"[""series_i"", ""venture""]",NaN,NaN,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,NaT,2024-07-08 02:00:00+02:00,NaN,NaN,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,NaT,2024-04-18 02:00:00+02:00,NaN,NaN,[],NaN,NaN,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,NaT,2024-03-26 01:00:00+01:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,NaT,2024-05-09 02:00:00+02:00,NaN,NaN,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,NaT,2024-07-16 02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,NaT,2024-07-15 02:00:00+02:00,NaN,NaN,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,NaT,2024-06-05 02:00:00+02:00,NaN,NaN,[],NaN,NaN,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,NaT,2024-06-27 02:00:00+02:00,Series A2,series_a2,"[""series_a2"", ""venture""]",NaN,NaN,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,NaT,2024-04-25 02:00:00+02:00,NaN,NaN,[],NaN,NaN,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,NaT,2024-04-10 02:00:00+02:00,NaN,NaN,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-20 02:00:00+02:00,2024-06-18 02:00:00+02:00,NaN,NaN,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24 02:00:00+02:00,2024-04-24 02:00:00+02:00,NaN,NaN,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,NaT,2024-06-25 02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26 02:00:00+02:00,2024-06-26 02:00:00+02:00,NaN,NaN,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,NaT,2024-04-30 02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",NaN,NaN,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27 02:00:00+02:00,2024-06-27 02:00:00+02:00,Series A,series_a,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,NaT,2024-05-22 02:00:00+02:00,NaN,NaN,"[""private_equity"", ""venture""]",NaN,NaN,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,NaT,2024-06-25 02:00:00+02:00,NaN,NaN,[],NaN,NaN,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [29]:
# rename all columns name
df.columns = df.columns.str.lower().str.replace(" ","_")
df

,website_domain,effective_date,found_at,financing_type,financing_type_normalized,categories,investors,investors_count,amount,amount_normalized,source_urls
0,trafigura.com,NaT,2024-03-14 01:00:00+01:00,NaN,NaN,[],accelia.vc,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,NaT,2024-05-31 02:00:00+02:00,NaN,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,NaT,2024-07-24 02:00:00+02:00,NaN,NaN,"[""private_equity""]",accelia.vc,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,NaT,2024-05-01 02:00:00+02:00,NaN,NaN,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,NaT,2024-04-11 02:00:00+02:00,NaN,NaN,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-18 02:00:00+02:00,2024-04-24 02:00:00+02:00,Series B,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16 02:00:00+02:00,2024-04-16 02:00:00+02:00,NaN,NaN,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,NaT,2024-08-07 02:00:00+02:00,Series I,series_i,"[""series_i"", ""venture""]",accelia.vc,NaN,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,NaT,2024-07-08 02:00:00+02:00,NaN,NaN,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,NaT,2024-04-18 02:00:00+02:00,NaN,NaN,[],accelia.vc,NaN,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,NaT,2024-03-26 01:00:00+01:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,NaN,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,NaT,2024-05-09 02:00:00+02:00,NaN,NaN,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,NaT,2024-07-16 02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,NaN,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,NaT,2024-07-15 02:00:00+02:00,NaN,NaN,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,NaT,2024-06-05 02:00:00+02:00,NaN,NaN,[],accelia.vc,NaN,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,NaT,2024-06-27 02:00:00+02:00,Series A2,series_a2,"[""series_a2"", ""venture""]",accelia.vc,NaN,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,NaT,2024-04-25 02:00:00+02:00,NaN,NaN,[],accelia.vc,NaN,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,NaT,2024-04-10 02:00:00+02:00,NaN,NaN,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-20 02:00:00+02:00,2024-06-18 02:00:00+02:00,NaN,NaN,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24 02:00:00+02:00,2024-04-24 02:00:00+02:00,NaN,NaN,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,NaT,2024-06-25 02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,NaN,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26 02:00:00+02:00,2024-06-26 02:00:00+02:00,NaN,NaN,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,NaT,2024-04-30 02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,NaN,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27 02:00:00+02:00,2024-06-27 02:00:00+02:00,Series A,series_a,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,NaT,2024-05-22 02:00:00+02:00,NaN,NaN,"[""private_equity"", ""venture""]",accelia.vc,NaN,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,NaT,2024-06-25 02:00:00+02:00,NaN,NaN,[],accelia.vc,NaN,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   website_domain             26 non-null     object
 1   effective_date             6 non-null      datetime64[ns, UTC+02:00]
 2   found_at                   26 non-null     object
 3   financing_type             8 non-null      object
 4   financing_type_normalized  8 non-null      object
 5   categories                 26 non-null     object
 6   investors                  26 non-null     object
 7   investors_count            13 non-null     float64
 8   amount                     26 non-null     object
 9   amount_normalized          26 non-null     int64
 10  source_urls                26 non-null     object
dtypes: datetime64[ns, UTC+02:00](1), float64(1), int64(1), object(8)
memory usage: 2.4+ KB

In [26]:
df

,website_domain,effective_date,found_at,financing_type,financing_type_normalized,categories,investors,investors_count,amount,amount_normalized,source_urls
0,trafigura.com,NaT,2024-03-14 01:00:00+01:00,NaN,NaN,[],accelia.vc,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,NaT,2024-05-31 02:00:00+02:00,NaN,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,NaT,2024-07-24 02:00:00+02:00,NaN,NaN,"[""private_equity""]",accelia.vc,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,NaT,2024-05-01 02:00:00+02:00,NaN,NaN,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,NaT,2024-04-11 02:00:00+02:00,NaN,NaN,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-18 02:00:00+02:00,2024-04-24 02:00:00+02:00,Series B,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16 02:00:00+02:00,2024-04-16 02:00:00+02:00,NaN,NaN,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,NaT,2024-08-07 02:00:00+02:00,Series I,series_i,"[""series_i"", ""venture""]",accelia.vc,NaN,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,NaT,2024-07-08 02:00:00+02:00,NaN,NaN,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,NaT,2024-04-18 02:00:00+02:00,NaN,NaN,[],accelia.vc,NaN,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,NaT,2024-03-26 01:00:00+01:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,NaN,$6.7 million,6700000,https://www.geekwire.com/2024/seattle-startup-...
11,canva.com,NaT,2024-05-09 02:00:00+02:00,NaN,NaN,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
12,syntetica.co,NaT,2024-07-16 02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,NaN,Û4.2 million,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,NaT,2024-07-15 02:00:00+02:00,NaN,NaN,[],eib.org,1.0,Û425 million,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,NaT,2024-06-05 02:00:00+02:00,NaN,NaN,[],accelia.vc,NaN,$10M,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,NaT,2024-06-27 02:00:00+02:00,Series A2,series_a2,"[""series_a2"", ""venture""]",accelia.vc,NaN,USD 31M,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,NaT,2024-04-25 02:00:00+02:00,NaN,NaN,[],accelia.vc,NaN,$5M,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,NaT,2024-04-10 02:00:00+02:00,NaN,NaN,"[""private_equity""]",vistaragrowth.com,1.0,$24.6 million CAD,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-20 02:00:00+02:00,2024-06-18 02:00:00+02:00,NaN,NaN,"[""private_equity""]",accelia.vc,1.0,$1.6M,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24 02:00:00+02:00,2024-04-24 02:00:00+02:00,NaN,NaN,"[""private_equity""]","edc.ca, desjardinscapital.com, fondsftq.com",3.0,$17.4 million,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,NaT,2024-06-25 02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,NaN,CAD$2.5M,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
21,claritisoftware.com,2024-06-26 02:00:00+02:00,2024-06-26 02:00:00+02:00,NaN,NaN,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,NaT,2024-04-30 02:00:00+02:00,Seed,seed,"[""seed"", ""venture""]",accelia.vc,NaN,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
23,gaiia.com,2024-06-27 02:00:00+02:00,2024-06-27 02:00:00+02:00,Series A,series_a,"[""series_a"", ""venture""]",inovia.vc,1.0,US$13.2M,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,NaT,2024-05-22 02:00:00+02:00,NaN,NaN,"[""private_equity"", ""venture""]",accelia.vc,NaN,$2.5M,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...
25,topicflow.com,NaT,2024-06-25 02:00:00+02:00,NaN,NaN,[],accelia.vc,NaN,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

In [24]:
df.to_csv('Processed Business Funding Data.csv', index=False)

## 1. Observations from Exploring the Data

While exploring the Business Funding Data, several important observations were made:

- The dataset contains multiple columns with missing values across both categorical and numerical variables.

- Some columns have a very high percentage of missing values, which reduces their usefulness for analysis.

- The dataset does not contain significant duplicate records, indicating that the entries are largely unique.

- A few numerical columns show large variations in values, which may influence statistical measures such as the mean.

- Some categorical columns contain repeated categories, making them suitable for imputation using the most frequent value.

These observations highlighted the need for careful handling of missing data and column relevance before performing further analysis.

## 2. Steps Taken to Clean, Preprocess, and Transform the Data

To prepare the dataset for analysis, the following preprocessing steps were applied:

### Handling Missing Values

- Missing values in categorical columns were replaced using the mode (most frequent value).

- Missing values in numerical columns were also filled using the mode, since the distribution suggested that the most common value better represents the data than the mean.

### Dropping Irrelevant Columns

- Columns with more than 70% missing values were removed from the dataset.

- These columns were considered not useful for meaningful analysis due to the large amount of missing information.

### Data Inspection

- The dataset was inspected to confirm that there were no duplicate rows.

- Data types and column structures were checked to ensure consistency.

After these preprocessing steps, the dataset became cleaner and more suitable for further exploratory data analysis and modeling.

## 3. Justification for the Techniques Used

The preprocessing techniques applied were chosen based on the nature of the dataset:

### Mode Imputation for Categorical Data
Since categorical variables cannot be averaged, the mode (most frequent value) is an appropriate way to replace missing entries while preserving the category distribution.

### Mode Imputation for Numerical Data
Some numerical columns contained outliers or extremely large values. Using the mean in such cases could distort the dataset. Therefore, using the mode helped maintain a more realistic representation of the data.

### Dropping Columns with Excessive Missing Values
Columns with over 70% missing data provide very limited information and may introduce noise into the analysis. Removing them improves overall data quality and reliability.

These decisions helped maintain data integrity while minimizing bias introduced during preprocessing.

## 4. Reflection on the Importance of Data Preprocessing

Data preprocessing is a critical step in real-world data analysis because raw data is often incomplete, inconsistent, or noisy.

Proper preprocessing ensures that:

- The dataset is accurate and reliable

- Analytical results are valid and meaningful

- Models built on the data produce better predictions and insights

Without proper preprocessing, analysis may lead to misleading conclusions or poor decision-making.

This exercise demonstrated how handling missing values, removing irrelevant columns, and understanding data structure are essential steps in transforming raw data into a usable dataset for analysis and visualization.